package c3s.blog.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

//import javax.validation.constraints.NotNull;
import java.util.List;

@Setter
@Getter
//@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "blogDetails")
public class BlogDetails {

    @Id
    @DynamoDBAttribute
    @DynamoDBIgnore
    PrimaryKey primaryKey;

    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute
    User user;

    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute
    Post post;
//
    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    Comment comments;
//
    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    User follower;

    public BlogDetails() {
    }

    public BlogDetails(User user) {
        this.user = user;
    }

    public BlogDetails( User user, Post post) {
        this.user = user;
        this.post = post;
    }

    public BlogDetails(User user, Post post, Comment comments) {
        this.user = user;
        this.post = post;
        this.comments = comments;
    }

    public BlogDetails(User user, Post post, Comment comments, User follower) {
        this.user = user;
        this.post = post;
        this.comments = comments;
        this.follower = follower;
    }

    @DynamoDBHashKey
    @DynamoDBAttribute
    public String getHashKey() {
        return primaryKey != null ? primaryKey.getHashKey() : null;
    }

    public void setHashKey(final String partitionKey) {
        if (primaryKey == null) {
            primaryKey = new PrimaryKey();
        }
        primaryKey.setHashKey(partitionKey);
    }

    @DynamoDBRangeKey
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    public String getRangeKey() {
        return primaryKey != null ? primaryKey.getRangeKey() : null;
    }

    public void setRangeKey(final String sortKey) {
        if (primaryKey == null) {
            primaryKey = new PrimaryKey();
        }
        primaryKey.setRangeKey(sortKey);
    }

    @DynamoDBIndexRangeKey(localSecondaryIndexName = "userName")
    public String getUserName(){
        return user==null ? null:user.getUserName();
    }

    public void setUserName(String userName){
        if(user == null){
            user = new User();
        }
        user.setUserName(userName);
    }


}
