package c3s.blog.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.List;
import java.util.UUID;

//@Table
//@Entity
@Setter
@Getter
@DynamoDBDocument
public class Post {//implements Serializable {

//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Column(name = "id")
//    @DynamoDBAutoGeneratedKey
//    @DynamoDBHashKey
//    String id;
//
//    @ManyToOne
//    @JoinColumn(name = "user_id" , nullable = false)
//    User creator;

//    @OneToMany(mappedBy = "post", cascade = CascadeType.REMOVE)
//    @JsonIgnore
//    List<Comment> comments;

//    @Column(name = "text", nullable = false)
    @DynamoDBAttribute
    String text;

    public Post() {
    }

    public Post(String text) {
//        this.creator = creator;
        this.text = text;
    }

//    public String getId() {
//        return id;
//    }

//    public User getCreator() {
//        return creator;
//    }

//    public List<Comment> getComments() {
//        return comments;
//    }

    public void setText(String text) {
        this.text = text;
    }
}
