package c3s.blog.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

@Getter
@Setter
//@NoArgsConstructor
@AllArgsConstructor
//    @DynamoDBDocument
public class PrimaryKey {

    @DynamoDBHashKey
    @DynamoDBAttribute
    private String hashKey;

    @DynamoDBRangeKey
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    private String rangeKey;

    public PrimaryKey() {
    }

    public PrimaryKey(String hashKey) {
        this.hashKey = hashKey;
    }

}